#!/bin/bash
# My mac config


# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set computer name (as done via System Preferences → Sharing)
#sudo scutil --set ComputerName "xbeqij"
#sudo scutil --set HostName "xbeqij"
#sudo scutil --set LocalHostName "xbeqij"
#sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "xbeqij"

# xcode devel tools for compilers
xcode-select --install

# Homebrew package management
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Set DNS
networksetup -setdnsservers Wi-Fi 185.228.168.10 185.228.169.11

# Hide Dock
defaults write com.apple.Dock autohide-delay -float 0.0001; killall Dock

# Hide menu bar

# Git config
git config --global user.email "ryan.horrisberger@wisc.edu"
git config --global user.name "Ryan Horrisberger"


# macOS settings


# AppStore (mas or gui)
# Microsoft Todo
# Microsoft remote desktop
# Annotate


# Other
# Install Office


#.zshrc files
#.vim stuff
# make this mac only stuff, linux stuff can go elsewhere

# configure:
# google drive sync, slack, pianobar, fantastical, office, 
# microsoft remote desktop, sign in to firefox

# firefox plugins
# mail signature
# customize trackpad double click, capslock->control
#oh my zsh
#eduroam cert
#citrix workspace
#global protect vpn